stages:
  - build
  - deploy

# was getting "server misbehaving" and problems running docker in docker
# fixed with https://stackoverflow.com/a/60395318

build_testing:
  stage: build
  only:
    - testing
  needs: []
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - (cd $CI_PROJECT_DIR && sh ./set-version.sh)
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE/testing --cache --cache-repo $CI_REGISTRY_IMAGE/cache
  tags:
    - general

# needs:[] enables this build to run in parallel while the build above is also running
build_debug:
  stage: build
  only:
    - testing
  needs: []
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - (cd $CI_PROJECT_DIR && sh ./set-version.sh)
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.debug --destination $CI_REGISTRY_IMAGE/debug --cache --cache-repo $CI_REGISTRY_IMAGE/cacheD
  tags:
    - general

build_release:
  stage: build
  only:
    - master
  needs: []
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: ['']
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - (cd $CI_PROJECT_DIR && sh ./set-version.sh)
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile.debug --destination $CI_REGISTRY_IMAGE/release:latest --destination $CI_REGISTRY_IMAGE/release:$CI_COMMIT_SHORT_SHA --cache --cache-repo $CI_REGISTRY_IMAGE/cacheM
  tags:
    - general

deploy:
  stage: deploy
  only:
    - testing
    - master
  image:
    name: curlimages/curl
  script:
    - curl -X POST --fail -F token=$PIPELINE_TRIGGER_TOKEN -F ref=main https://gitlab.labranet.jamk.fi/api/v4/projects/18735/trigger/pipeline
  tags:
    - general
